require 'shellwords'

task default: %i[jupyter]

task jupyter: ['jupyter:tests']

namespace :jupyter do
  task tests: [:jupyter]

  task :test_jupter do
    jupyter_tests_file = File.join(__dir__, 'jupyter/tc_jupyter.rb')
    ruby Shellwords.escape(jupyter_tests_file)
  end
end
