require 'shellwords'

task default: %i[python]

task python: ['python:tests']

namespace :python do
  task tests: [:test_jupyter]

  task :test_jupyter do
    jupyter_tests_file = File.join(__dir__, 'tc_jupyter.rb')
    ruby Shellwords.escape(jupyter_tests_file)
  end
end
